### ISSUE TITLE
missing fem_example.cpp

### ISSUE THREAD

**Issue by ngc1** [barche/eigen-proto#1]
Hi Bart, Thanks for the awesome work. I was also reading your paper "Finite Element Assembly Using an Embedded Domain Specific Language". In that and also here : https://github.com/barche/eigen-proto , the fem_example.cpp is missing or is deleted. Could you kindly upload it again or point to an equivalent example please? greatly appreciate your help.

Regards.

**Comment by barche** [comment]
Sorry, it seems I renamed it to `fem_mass_matrix.cpp`:
https://github.com/barche/eigen-proto/blob/master/fem_mass_matrix.cpp

Nice to know someone read my article :)

**Comment by ngc1** [comment]
Thanks Bart, of course :), your work is my inspiration now for me to work
on proto based DSEL for multi-physics solver. Thanks again for the update.

Regards

**Comment by barche** [comment]
Great! I should note that I'm currently looking at Julia for my future work:
http://julialang.org/
It is (with some care) as fast as C++, but a lot more pleasant for metaprogramming. It's worth checking out, depending on how tied to C++ and how far in your project you are.

**Comment by ngc1** [comment]
Thank you Bart, seems very interesting, will try to use it when you say it
is easier for metaprogramming. Thanks again.

Regards.
